[tool.poetry]
name = "langchain_jupyter"
version = "0.1.0"
description = ""
authors = ["Masato Shimizu <ma6ato@gmail.com>"]
readme = "README.md"
packages = [{ include = "langchain_jupyter", from = "src" }]

[tool.poetry.dependencies]
python = "3.11.7"
notebook = "7.0.6"
python-dotenv = "1.0.0"
openai = "1.6.1"
langchain = "0.0.353"


[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"
taskipy = "1.12.2"
mypy = "1.8.0"
ruff = "0.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test = "pytest tests"
mypy = "mypy src tests"
ruff = "task ruff-check && task ruff-format"
ruff-check = "ruff check src --fix"
ruff-format = "ruff format src"
