[tool.poetry]
name = "langchain-jupyter"
version = "0.1.0"
description = ""
authors = ["Masato Shimizu <ma6ato@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
notebook = "^7.0.6"
python-dotenv = "^1.0.0"
openai = "^1.6.1"
langchain = "^0.0.353"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
