[tool.poetry]
name = "langchain_jupyter"
version = "0.1.0"
description = ""
authors = ["Masato Shimizu <ma6ato@gmail.com>"]
readme = "README.md"
packages = [{ include = "langchain_jupyter", from = "src" }]

[tool.poetry.dependencies]
python = "3.11.7"
notebook = "7.0.6"
python-dotenv = "1.0.0"
openai = "1.6.1"
langchain = "0.0.354"
pymupdf = "1.23.8"
slack-bolt = "1.18.1"
momento = "1.16.0"
boto3 = "1.34.13"
streamlit = "1.29.0"
duckduckgo-search = "4.1.1"
wikipedia = "1.4.0"
spacy = "3.7.2"
tiktoken = "0.5.2"
chromadb = "0.4.22"
chainlit = "0.7.700"


[tool.poetry.group.dev.dependencies]
pytest = "7.4.4"
taskipy = "1.12.2"
mypy = "1.8.0"
ruff = "0.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test = "pytest tests"
mypy = "mypy src tests"
ruff = "task ruff-check && task ruff-format"
ruff-check = "ruff check src --fix"
ruff-format = "ruff format src"
