---
name: Create a pull request for release.

on:
  push:
    branches: [stage, develop]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Check if pr exists
        id: check_pr
        run: |
          pr_title=${{ (github.ref == 'refs/heads/stage' && 'Stage') || 'Develop' }}
          base_branch=${{ (github.ref == 'refs/heads/stage' && 'main') || 'stage' }}

          echo "count=$(gh pr list -S ${pr_title}' in:title' -B $base_branch | wc -l)" >> $GITHUB_OUTPUT
          echo "pr_title=$pr_title" >> $GITHUB_OUTPUT
          echo "base_branch=$base_branch" >> $GITHUB_OUTPUT

      - name: Create release pr
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create -B ${{ steps.check_pr.outputs.base_branch }} -t ${{ steps.check_pr.outputs.pr_title }} -b ""
